### ISSUE TITLE
Add RNN, LSTM

### ISSUE THREAD

**Issue by josephjaspers** [josephjaspers/BlackCat_Tensors#18]

**Comment by xinsuinizhuan** [comment]
yes。lstm and rnn is best method to forecast! You are best! I am your fans!

**Comment by xinsuinizhuan** [comment]
Add RNN, LSTM?? whether to support CNN and LSTM？？

**Comment by josephjaspers** [comment]
Completed RNN, Working on LSTM next. 

https://github.com/josephjaspers/BlackCat_Tensors/commit/306872c75ae2ad4c493728baf8c69645af7d322e
https://github.com/josephjaspers/BlackCat_Tensors/commit/0916fa46b2012bd90b005d8c3c7a920aeef3140e
https://github.com/josephjaspers/BlackCat_Tensors/commit/2377260ddc4197a7a7a5f7f1d5ed07fbf51ad9ae

**Comment by josephjaspers** [comment]
Added LSTM (experimental)
https://github.com/josephjaspers/BlackCat_Tensors/commit/58ae98630e417b459f4a216e2312f31e0ff28756

LSTM is experimental. 
I need to check and make sure the math for it is correct, it seems to be relatively working with the given example, though it performs worse than the plain recurrent layer.

**Comment by xinsuinizhuan** [comment]
OK, thats in part good news。Others,  i hope the trained modle could save, and when need, i only load model to predict.

**Comment by josephjaspers** [comment]
I will definitely add that soon, if you could give me a list of features you want I will try to implement them as fast as possible.

**Comment by xinsuinizhuan** [comment]
> 
> 
> I will definitely add that soon, if you could give me a list of features you want I will try to implement them as fast as possible.

I want use the net to forecast the short-term-load for Electric-Power,as the net at https://github.com/YuanSiping/Short-Term-Load-Forecasting-for-Electric-Power-Systems
main supprot net:
1、cnn
2、lstm

But, i need the trained net support save and load net,as the net at https://github.com/Artelnics/OpenNN.
main supprot function:
1、save the trained model
2、load the saved trained model to predit
3、the best support the net could continue trained.

**Comment by josephjaspers** [comment]
Closing this issue as RNN/LSTM have been added.

Added a ticket for training/saving here:
https://github.com/josephjaspers/BlackCat_Tensors/issues/25
