### ISSUE TITLE
Add Support for Visual Studio Compiler (14+)

### ISSUE THREAD

**Issue by josephjaspers** [josephjaspers/BlackCat_Tensors#19]

**Comment by xinsuinizhuan** [comment]
Yes.Need to support Visual Studio Compiler，then i will open the project by Visual Studio 12，then compiler the project!

**Comment by josephjaspers** [comment]
Added support for Visual Studio 2019
https://github.com/josephjaspers/BlackCat_Tensors/commit/b0e562f7b91a45903bba99e7eb158f586ec3cfe0
