### ISSUE TITLE
Add support for VisualStudio and Cuda 

### ISSUE THREAD

**Issue by josephjaspers** [josephjaspers/blackcat_tensors#22]

**Comment by xinsuinizhuan** [comment]
It is a good new for me to support VS compile. But when i test use my enrironment VisualStudio 2015 64, still some errors. 
1、when is compile it, tip array<1,int>={0}, is error,like below:
![1563929916(1)](https://user-images.githubusercontent.com/40679769/61758752-9ed89700-adf8-11e9-9cfc-9d4bf702f38f.jpg)
2、then i remove the {0} and {1},，some more errors it appera:
![1563931274(1)](https://user-images.githubusercontent.com/40679769/61758800-d34c5300-adf8-11e9-9df1-833b5f980270.jpg)
3、then i pack my project ,and send to you, please check if it is set error!
[BlackCat_Tensors-master.zip](https://github.com/josephjaspers/BlackCat_Tensors/files/3424682/BlackCat_Tensors-master.zip)

**Comment by xinsuinizhuan** [comment]
I send you my VS2015 project, i can compile normally? vs2019 can open vs2015 project, you only open /source/BlackCat_Tensors.sln,then compile it, whether it can compile normally?

**Comment by josephjaspers** [comment]
I've just downloaded VS2015. I will see what changes need to be made.

**Comment by josephjaspers** [comment]
Hi, VS2015 does not support some of the features required to compile this code. 

Constexpr expressions are used quite frequently and supporting VS15 would require changing most of the code. 

The code does compile on VS2019 Community edition.

**Comment by xinsuinizhuan** [comment]
Thank you! I have downloaded vs2019 to compile my project. But when i run MNIST_TEST example, it crashed at line 44 in host.h, as follow:
![1564622033(1)](https://user-images.githubusercontent.com/40679769/62258780-665f3b80-b43e-11e9-91e2-128aef26765a.jpg)
![1564622607(1)](https://user-images.githubusercontent.com/40679769/62258783-695a2c00-b43e-11e9-8b2f-87df5cc123b6.jpg)

**Comment by josephjaspers** [comment]
Thank you for reporting that bug!
Seems I was only testing under 'release' mode.

 The code works as expected in Release mode though I  will try to fix that bug.

**Comment by josephjaspers** [comment]
Hi, I simply replaced "BC::memory::atomic_shared_ptr" with 'std::shared_ptr' 
(the atomic feature is not commonly needed anyway). 

Should work in debug mode, though I recommend compiling in release mode as it is very slow in debug mode.

**Comment by xinsuinizhuan** [comment]
I run the newest code in debug and release, but also crashed!
![1564709345(1)](https://user-images.githubusercontent.com/40679769/62337795-a7bc1d80-b508-11e9-9f44-931324431759.jpg)
vs2019, windows10,cuda10.1 cudnn7.4

**Comment by xinsuinizhuan** [comment]
![1564709345(1)](https://user-images.githubusercontent.com/40679769/62337823-c3272880-b508-11e9-8a5e-0ba10c077e39.jpg)

**Comment by xinsuinizhuan** [comment]
I debug this problem,  it break at openblas, i did don't know why?
![1564713445(1)](https://user-images.githubusercontent.com/40679769/62340316-c8d53c00-b511-11e9-9bc8-55d4174aee57.jpg)

**Comment by josephjaspers** [comment]
OpenBLAS does not always work with other programs that use open mp. 
You can try to use... 

#define BC_NO_OPENMP 

before including "BlackCat_Tensors.h"

**Comment by josephjaspers** [comment]
Alternatively according to https://github.com/xianyi/OpenBLAS/wiki/faq

**Comment by xinsuinizhuan** [comment]
> 
> 
> OpenBLAS does not always work with other programs that use open mp.
> You can try to use...
> 
> #define BC_NO_OPENMP
> 
> before including "BlackCat_Tensors.h"

I try:  
#define BC_NO_OPENMP
before including "BlackCat_Tensors.h"
but still crashed! Let me try compile OpenMP with USE_OPENMP=1.
Or what your OpenMp version is? Could you send me your OpenMP include and .lib, let me have a try?

**Comment by xinsuinizhuan** [comment]
I compile the OpenMP with USE_OPENMP=1, then i run vs2019 project, it still crashed. Then i set the vs2019 project with USE_OpenMP，compile, some errors, below:
![1564741893(1)](https://user-images.githubusercontent.com/40679769/62364343-c7c4fe80-b553-11e9-8c13-499a44cbcdca.jpg)

**Comment by xinsuinizhuan** [comment]
Could you sent me you Openblas file (include lib)  in windows to me, let me have a try??

**Comment by josephjaspers** [comment]
I will see what I can do. 
I currently test Windows10 with MKL so you could try that instead of openblas. 
I will try to see if I can get openblas to work.

**Comment by xinsuinizhuan** [comment]
what is MKL? how to work with MKL? I set project MNIST_Test project OpenMP is true, then some errors is appear, line 218 in BlackCat_Common.h file. below:
![1564973112(1)](https://user-images.githubusercontent.com/40679769/62435281-2665c480-b76e-11e9-8ab0-7eeac1de8f0f.jpg)

**Comment by xinsuinizhuan** [comment]
The crashed is still, when I seted openblas OpenMP is true, And Set #define BC_NO_OPENMP
before including "BlackCat_Tensors.h"! Others i compelie the mnist_test_recurrent hava some errors.

**Comment by josephjaspers** [comment]
Intel MKL
https://software.intel.com/en-us/mkl/features/linear-algebra

If you define BC_NO_OPENMP than all open-mp features should be disabled.
Therefor the issue would be with openblas and not BlackCat_Tensors.

In line 194 in BlackCat_Common.h you can see the features being disabled.

**Comment by xinsuinizhuan** [comment]
Yes, I konw! But when i set openmp is true, some compiles is some errors!

**Comment by xinsuinizhuan** [comment]
Yes, I konw! But when i set openmp is true, compiles it appear some errors, it should not appear!

**Comment by xinsuinizhuan** [comment]
I install w_mkl_2019.4.245.exe,then what should i do ? which  xx.lib file is additional dependencies?

**Comment by xinsuinizhuan** [comment]
I test the openblas Independently，it work normally! I create a new project, I cmake the OpenBlas，then include the "lapack-netlib\CBLAS\include" in my project and link the "lib\RELEASE\openblas.lib" and "lib\DEBUG\openblas.lib" to my new project, then i run the below code, it work normally:

int test()
{
	float a[1] = { 2 };
	float b[1] = { 3 };
	float c[1] = { 0 };
	cblas_sgemm(CblasRowMajor,
		CblasNoTrans, CblasNoTrans,
		1, 1, 1,
		1,
		a, 1,
		b, 1,
		0,
		c, 1);
	std::cout << *c << std::endl;

	system("pause");
	return 0;
}

**Comment by xinsuinizhuan** [comment]
But your project when i run the cblas_dgemm, it crashs, line 182 in host.h.
![E@U%X~T9F~)8}1C ERV4LYW](https://user-images.githubusercontent.com/40679769/62450156-59c04780-b79e-11e9-85ed-f2077b6a43a1.png)
![H`M(V~@D@R 7}Q_54I}}XBS](https://user-images.githubusercontent.com/40679769/62450157-59c04780-b79e-11e9-8004-71a03338df21.png)


This is my openblas include file and .lib file (cmake openblas, the get them, vs2019, windows10), you can hava a try, to find where is wrong?
[openblas.zip](https://github.com/josephjaspers/BlackCat_Tensors/files/3466610/openblas.zip)

**Comment by josephjaspers** [comment]
I will look into it.

**Comment by xinsuinizhuan** [comment]
I use the https://github.com/xianyi/OpenBLAS/issues/805 openblas036-win64.zip it works normally. So the problem is the openlabs, then you can focus on the net crnn and  lstm! Thank you!
