### ISSUE TITLE
Question: What is BC::tensors::Tensor_Base<internal_t> / how to get values of Tensor ?

### ISSUE THREAD

**Issue by xinsuinizhuan** [josephjaspers/blackcat_tensors#31]
I print the average loss，but the BC can not implicit conversion to double?
![1567474331(1)](https://user-images.githubusercontent.com/40679769/64138043-bc544400-ce2d-11e9-93f5-db91476faf44.jpg)

**Comment by josephjaspers** [comment]
BC::nn::MAPE returns an "expression object" (opposed to a primitive data type).

All operations/expressions with Tensors return `expression objects.` 
Originally `BC::sum` returned a scalar (double, float, or int) however this was inconsistent with the rest of the framework. 

To get the value you can do something like....

`double error = BC::Scalar<double>(BC::nn::MAPE(hyps, outputs)).data()[0]`

BC::Scalar<double> will evaluate the expression BC::nn::MAPE(hyps, outputs)
.data() //returns the internal pointer (IE double*) 
[0] //gets the first value of the pointer

**Comment by josephjaspers** [comment]
What you could do if you just want to log the error would be....
std::cout << (BC::nn::MAPE(hyps, outputs[0]) / batch_size).to_string() << std::endl;

**Comment by xinsuinizhuan** [comment]
Oh, i see !Thank you!

**Comment by xinsuinizhuan** [comment]
> 
> 
> BC::nn::MAPE returns an "expression object" (opposed to a primitive data type).
> 
> All operations/expressions with Tensors return `expression objects.`
> Originally `BC::sum` returned a scalar (double, float, or int) however this was inconsistent with the rest of the framework.
> 
> To get the value you can do something like....
> 
> `double error = BC::Scalar<double>(BC::nn::MAPE(hyps, outputs)).data()[0]`
> 
> BC::Scalar will evaluate the expression BC::nn::MAPE(hyps, outputs)
> .data() //returns the internal pointer (IE double*)
> [0] //gets the first value of the pointer

when i use the below, run it, it break:
	double error = BC::Scalar<double>(BC::nn::MAPE(hyps, outputs)).data()[0];
	double average_error = error / batch_size;
	std::cout << "Average loss: " << average_error << std::endl;
this line error：double error = BC::Scalar<double>(BC::nn::MAPE(hyps, outputs)).data()[0];
![1567557940(1)](https://user-images.githubusercontent.com/40679769/64217608-9b085c00-cef0-11e9-9587-ca01f09b6401.jpg)

**Comment by xinsuinizhuan** [comment]
> 
> 
> What you could do if you just want to log the error would be....
> std::cout << (BC::nn::MAPE(hyps, outputs[0]) / batch_size).to_string() << std::endl;

this expression is ok!

**Comment by josephjaspers** [comment]
What are you writing for this:

**Comment by xinsuinizhuan** [comment]
> BC::Scalar<double>(BC::nn::MAPE(hyps, outputs[0]) / batch_size).data()[0];

OK.below three methods is ok:
std::cout << (BC::Scalar<double>(BC::nn::MAPE(hyps, outputs[0]).data()[0]) / batch_size).to_string() << std::endl;

std::cout << BC::Scalar<double>(BC::nn::MAPE(hyps, outputs[0]) / batch_size).data()[0] << std::endl;

double error = (BC::Scalar<double>(BC::nn::MAPE(hyps, outputs[0])).data())[0];
double average_error = error / batch_size;
std::cout << "Average loss: " << average_error << std::endl;

**Comment by josephjaspers** [comment]
I believe you need to specify the <double> argument. (BC::Scalar<double>)
`BC::Scalar<double>(BC::nn::MAPE(hyps, outputs[0]) / batch_size).data()[0];`

Though I would expect a compile error not a runtime error.

**Comment by xinsuinizhuan** [comment]
One new problem, the newest code, mnist_test_recurrent example, compile it, error as:
![1567994394(1)](https://user-images.githubusercontent.com/40679769/64498774-b2788800-d2e8-11e9-8158-6780426e01c3.jpg)

**Comment by josephjaspers** [comment]
According to Microsoft:

"The C language allows implicit narrowing conversions in assignments and initialization, and C++ follows suit, even though unexpected narrowing is a cause of many code errors. To make code safer, the C++ standard requires a diagnostic message when a narrowing conversion occurs in an initialization list. In Visual C++, the diagnostic is Compiler Error C2397 when using the uniform initialization syntax supported beginning in Visual Studio 2015. The compiler generates Compiler Warning (level 1) C4838 when using the list or aggregate initialization syntax supported by Visual Studio 2013."

https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2397?view=vs-2019

So this should actually be a warning, however Visual Studio treats it as an error. 

This has been fixed as of:
https://github.com/josephjaspers/blackcat_tensors/commit/34a189142a720c5a7ad37aa0b628c189658892c5

**Comment by xinsuinizhuan** [comment]
Oh，i see.

**Comment by josephjaspers** [comment]
Yeah sorry about that, I'll try to add narrowing conversion as an error so I'll catch it next time.

**Comment by xinsuinizhuan** [comment]
narrowing conversion again:
![1569566669(1)](https://user-images.githubusercontent.com/40679769/65749014-d08f1680-e137-11e9-9b99-f5fd01101f7f.jpg)

**Comment by josephjaspers** [comment]
Good catch, thanks for that. I will make those changes soon

**Comment by josephjaspers** [comment]
Fixed with https://github.com/josephjaspers/blackcat_tensors/commit/582203819850d5f1df769a46bcea389edcee8690
