### ISSUE TITLE
How to put my data into the model?

### ISSUE THREAD

**Issue by xinsuinizhuan** [josephjaspers/blackcat_tensors#35]
I read my txt'file data to the vector, then when i put my vectror data to the model, compile, it error:

![1569749104(1)](https://user-images.githubusercontent.com/40679769/65830034-6664a600-e2de-11e9-9d14-25c32f5de90c.jpg)
 how should i do?

I add the under function to Tensor_Utility.h, and it compile normal, is it ok?
	void data_format_convers(std::vector<double> & maxmindata) {
		std::vector<value_type> file_data;

		for (int i = 0; i < maxmindata.size(); i++)
		{
			value_type val = (value_type)maxmindata[i];
			file_data.push_back(val);
		}
		int copy_size = (unsigned)as_derived().size() > file_data.size() ? file_data.size() : as_derived().size();
		utility_l::HostToDevice(as_derived().internal().memptr(), file_data.data(), copy_size);
	}

**Comment by josephjaspers** [comment]
Seems good for now. The only issue I can think of is that it won't work for non-continuous tensors.
Feel free to make a pull-request on any features you want to add.

**Comment by josephjaspers** [comment]
Looks good to me! It seems that it won't work for non-continuous tensors (thought I will an nd-iterator to handle this later).

**Comment by josephjaspers** [comment]
It seems you are trying to assign a slice of a matrix to a `std::vector.` You can assign element-by-element though.

```
	BC::Cube<float> data_cube(4,2,1);
	std::vector<std::vector<float>> data = { {1,2,3,4}, {1,2,3,4}};


	for (std::size_t i = 0; i < data.size(); ++i) {
		for (std::size_t j = 0; j < data[i].size(); ++j) {
			data_cube[0][i][j] = data[i][j];
		}
	}
```

**Comment by xinsuinizhuan** [comment]
In addition, when i get the forward_propagation data, how could i put them into my vector?

mat hyps = network->m_pnetwork.forward_propagation(inputs[0]);

I want get the data from hyps to my vector and array? How should i do?

**Comment by josephjaspers** [comment]
You can use the algorithm to copy data (include/algorithms/Algorithms.h)

```
outputvec = std::vector(hyps.size()); 
BC::copy(hyps.get_stream(), outputvec.begin(), outputvec.end(), hyps.cw_begin()); 
```

Its nearly identical to std::copy if you are only using host_tensors though it is data-safe if you ever want to switch to GPU mode (cuda).

**Comment by xinsuinizhuan** [comment]
This seem not work, my code is:
![1570497240(1)](https://user-images.githubusercontent.com/40679769/66360043-22dbfd00-e9ac-11e9-9a1f-02875e768fd7.jpg)
when i compile it ,error. How should i do?

**Comment by xinsuinizhuan** [comment]
Yes， when i use :
	std::vector<double> predict_vec(hyps.size());
	BC::copy(hyps.get_stream(), predict_vec.begin(), predict_vec.end(), hyps.cw_begin());
that is ok! Thank you!
