### ISSUE TITLE
Debug model is so slow.

### ISSUE THREAD

**Issue by xinsuinizhuan** [josephjaspers/blackcat_tensors#39]
vs2019 debug model, to create network and load trained model file is so slow. load  trained model file > 5s.

**Comment by josephjaspers** [comment]
Debug mode is slower because it doesn't have any optimizations.
You can try to use /Zo in Visual Studio. (It has some optimizations to make it run faster, but not too many to make it hard to debug).

https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-optimized-code?view=vs-2019

**Comment by xinsuinizhuan** [comment]
> 
> 
> Debug mode is slower because it doesn't have any optimizations.
> You can try to use /Zo in Visual Studio. (It has some optimizations to make it run faster, but not too many to make it hard to debug).
> 
> https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-optimized-code?view=vs-2019

How about the compile errors, the newest code? I can't compile it by vs2019 now, i am so hurry!
![error](https://user-images.githubusercontent.com/40679769/66616233-83647780-ec02-11e9-86b6-27845408f2d9.png)
Could you repair it firstly?

**Comment by josephjaspers** [comment]
Fixed with:
https://github.com/josephjaspers/blackcat_tensors/commit/67b6673460ad8198dd007a6f0d2183ce29f390ed

**Comment by xinsuinizhuan** [comment]
> 
> 
> Fixed with:
> [67b6673](https://github.com/josephjaspers/blackcat_tensors/commit/67b6673460ad8198dd007a6f0d2183ce29f390ed)

NO,NO. I compile it, more errors:
![error_mode](https://user-images.githubusercontent.com/40679769/66620176-240e6380-ec12-11e9-9d39-0b7ea261d834.png)

**Comment by xinsuinizhuan** [comment]
> 
> 
> > Fixed with:
> > [67b6673](https://github.com/josephjaspers/blackcat_tensors/commit/67b6673460ad8198dd007a6f0d2183ce29f390ed)
> 
> NO,NO. I compile it, more errors:
> ![error_mode](https://user-images.githubusercontent.com/40679769/66620176-240e6380-ec12-11e9-9d39-0b7ea261d834.png)

some files is missing upload?

**Comment by xinsuinizhuan** [comment]
yes, it is ok now. I dowload the newest code, it ok!
but, could you fixed the https://github.com/josephjaspers/blackcat_tensors/issues/40 problem, i use the lstm mode, but could only train, can not forcast.

**Comment by josephjaspers** [comment]
Closing. 

Working on problem https://github.com/josephjaspers/blackcat_tensors/issues/40
