### ISSUE TITLE
Hurry!!! lstm back_propagation some errors.

### ISSUE THREAD

**Issue by xinsuinizhuan** [josephjaspers/blackcat_tensors#41]
My net is:
auto make_lstm_network() {
	return BC::nn::neuralnetwork(
		BC::nn::lstm(BC::host_tag(), 96 * 10, 1024),
		BC::nn::lstm(BC::host_tag(), 1024, 512),
		BC::nn::lstm(BC::host_tag(), 512, 256),
		BC::nn::recurrent(BC::host_tag(), 256, 192),
		BC::nn::output_layer(BC::host_tag(), 192)
	);
}
using network_type = decltype(make_lstm_network());

typedef struct _LstmPredictTask {
	int	                fd;		
	int			m_inputs_number;
	int			m_outputs_number;
	int			m_sequence_length;
	int			m_train_number;
	int	                m_batch_size;	
	double		m_learning_rate;	
	network_type		m_pnetwork = make_lstm_network();
	void reset_neural_network() {
		m_pnetwork = std::move(make_lstm_network());
	}
} LstmPredictTask;

i new a LstmPredictTask, then train, but when it run to lstm back_propagation, it break, but my input and output data size is right:
![图片](https://user-images.githubusercontent.com/40679769/66805297-357ba680-ef57-11e9-92d5-2f00c7cf1f1d.png)
break at this point:
![图片](https://user-images.githubusercontent.com/40679769/66805362-69ef6280-ef57-11e9-9966-94864a853ddf.png)
the console output is:
![图片](https://user-images.githubusercontent.com/40679769/66805437-9c00c480-ef57-11e9-975d-6cc2259b6834.png)
 i count my input data size, is right,960, and output data size, is right, 192

**Comment by josephjaspers** [comment]
Should be fixed,

**Comment by josephjaspers** [comment]
These should have said "output_size" instead 

![image](https://user-images.githubusercontent.com/20384345/66877499-af298980-ef83-11e9-8ed5-a171378dbec8.png)


Fixed as of:
https://github.com/josephjaspers/blackcat_tensors/commit/b560d25b4047c8f50742fc23aa86a29886ee2542
