### ISSUE TITLE
data conver precision problem!

### ISSUE THREAD

**Issue by xinsuinizhuan** [josephjaspers/blackcat_tensors#42]
I use this way to inputdata to system:
![图片](https://user-images.githubusercontent.com/40679769/66807753-5db9d400-ef5c-11e9-8a5b-3e225168e46c.png)

my original double data:
![图片](https://user-images.githubusercontent.com/40679769/66807947-c739e280-ef5c-11e9-9db8-7f7f01192b66.png)
when i conver it to inner:
![图片](https://user-images.githubusercontent.com/40679769/66807999-e20c5700-ef5c-11e9-9e03-2b8479bfce30.png)
my convered double data precision is %1f. How should i do?

**Comment by josephjaspers** [comment]
Are you sure the data is losing precision or is it just being output with a lower precision?


You can use
```
int precision = 5;
tensor.print(precision); 
```

To change the output precision. 

Likewise to copy data from a vector you could even just do... (assuming no cuda)
for (int i = 0; i < vector.size(); ++i) {
     tensor.data()[i] = vector[i]; 
}

Or better yet:
```
BC::copy(BC::Stream<system_tag>(), vector.begin(), vector.end(), tensor.cw_begin()); 
```

**Comment by xinsuinizhuan** [comment]
> BC::copy(BC::Stream<system_tag>(), vector.begin(), vector.end(), tensor.cw_begin());

OK. I am so sorry.Data conver precision is ok,i am use the "print(3)".

**Comment by josephjaspers** [comment]
No problem!
