### ISSUE TITLE
batch_size and samples size puzzle?

### ISSUE THREAD

**Issue by xinsuinizhuan** [josephjaspers/blackcat_tensors#44]
![图片](https://user-images.githubusercontent.com/40679769/67142755-eacf9680-f296-11e9-8ff5-7c6c5ba72fa2.png)
percept_MNIST function in mnist_test_recurrent example, batch_size==32, and samples=32X1024, but in my real data, the samples is not the batch_size's  multiple, for example, my data size is 32X1024+31, so the last 31 record is not trained?

**Comment by josephjaspers** [comment]
Yes! That is correct, you could load the data into a cube that is a multiple of 32 and just leave the last column empty (zeros).

**Comment by josephjaspers** [comment]
Eventually I would like to add "training" functions so that you wouldn't need to write the training step your self. (Like how pytorch has a 'fit' method)
