### ISSUE TITLE
New code compile error!

### ISSUE THREAD

**Issue by xinsuinizhuan** [josephjaspers/blackcat_tensors#52]
![图片](https://user-images.githubusercontent.com/40679769/69003345-d4226b00-093a-11ea-8ec5-3d1e07d27671.png)
whether the dim.h need add to the project?

**Comment by josephjaspers** [comment]
I don't have access to my windows partition right now, but hopefully I will be able to fix this soon.

**Comment by xinsuinizhuan** [comment]
It is ok now.Thank you!

**Comment by josephjaspers** [comment]
Fixed with: https://github.com/josephjaspers/blackcat_tensors/commit/7d284874ff9e874cb86d12a41b20c7cf81c729ee
